//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sati
    {
        public int SatisID { get; set; }
        public Nullable<int> RefSirketID { get; set; }
        public Nullable<int> RefMusteriID { get; set; }
        public Nullable<int> RefUrunID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string RefAspNetUserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
